name: PlayerSlotAPI
main: com.github.playerslotapi.PlayerSlotPlugin
authors:
  - YiMiner
  - StrawberryYu
version: ${version}
softdepend:
  - Vault
  - PlaceHolderAPI
  - DragonCore
  - GermPlugin
api-version: 1.13
commands:
  psapi:
    description: test command
    usage: /psapi