name: PlayerSlotApi
main: com.github.playerslotapi.PlayerSlotApi
author: YiMiner,StrawberryYu
version: ${project.version}
softdepend:
  - Vault
  - PlaceHolderAPI
  - DragonCore
  - GermPlugin
api-version: 1.13
commands:
  psapi:
    description: test command
    usage: /psapi